# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 06352e2
_src_path: cookie
backend: setuptools
email: jmaldonad@bnl.gov
full_name: Jennefer Maldonado
license: BSD
org: jennmald
project_name: nslsii
project_short_description: NSLS-II related devices
url: https://github.com/jennmald/nslsii
vcs: true
